"""Build a varied set of near-level opening positions for head-to-head runs.

tools/bench.py ships twelve positions, which caps a run at twenty-four distinct
games because both engines are deterministic. Past that point extra games are
the same games again and the confidence interval it prints is a lie.

The filter is our own evaluation at a shallow search, not an external engine.
That is fine for its purpose: both sides of a head-to-head share the same
evaluation, so "near level by our own reckoning" biases neither of them, and the
only property being asked of these positions is that they are level and varied.

    python3 -m tools.gen_openings --count 64 --out tools/openings.py
"""

from __future__ import annotations

import argparse
import random
import sys
from pathlib import Path

import chess

MAX_ABS_SCORE = 70  # centipawns; wider than this and the position picks a winner
MIN_PLIES = 4
MAX_PLIES = 10


def _quiet_enough(board: chess.Board) -> bool:
    """Reject positions that start mid-tactic rather than mid-opening."""
    if board.is_check() or board.is_game_over():
        return False
    # Nothing of value hanging: a position where one side simply wins a piece on
    # move one measures the opponent's first move, not the engines.
    for color in (chess.WHITE, chess.BLACK):
        for piece_type in (chess.QUEEN, chess.ROOK, chess.BISHOP, chess.KNIGHT):
            for square in chess.scan_forward(board.pieces_mask(piece_type, color)):
                if board.attackers_mask(not color, square) and not board.attackers_mask(
                    color, square
                ):
                    return False
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--count", type=int, default=64)
    parser.add_argument("--out", type=Path, default=Path("tools/openings.py"))
    parser.add_argument("--judge", type=Path, default=Path("versions/bot4"))
    parser.add_argument("--think-ms", type=int, default=250)
    parser.add_argument("--seed", type=int, default=20260903)
    arguments = parser.parse_args()

    sys.path.insert(0, str(arguments.judge.resolve()))
    import agent  # noqa: PLC0415  the judge is chosen at runtime

    generator = random.Random(arguments.seed)
    seen: set[str] = set()
    kept: list[str] = []
    attempts = 0

    while len(kept) < arguments.count and attempts < arguments.count * 60:
        attempts += 1
        board = chess.Board()
        for _ in range(generator.randint(MIN_PLIES, MAX_PLIES)):
            moves = list(board.legal_moves)
            if not moves:
                break
            # Prefer developing moves over random shuffling, so the set looks
            # like openings rather than like noise.
            weighted = [
                move
                for move in moves
                for _ in range(3 if board.piece_type_at(move.from_square) != chess.KING else 1)
            ]
            board.push(generator.choice(weighted))
        if not _quiet_enough(board):
            continue
        fen = board.fen()
        if fen in seen:
            continue

        agent._board = None
        agent._history_keys = []
        agent._tt.clear()
        agent.get_move(fen, arguments.think_ms)
        # A short search from both sides; keep only positions neither side likes
        # much better than the other.
        score = agent.evaluate(board)
        if abs(score) > MAX_ABS_SCORE:
            continue

        seen.add(fen)
        kept.append(fen)

    body = ['"""Generated by tools/gen_openings.py. Near-level, varied, deterministic."""', ""]
    body.append("OPENINGS: tuple[str, ...] = (")
    for fen in kept:
        body.append(f'    "{fen}",')
    body.append(")")
    arguments.out.write_text("\n".join(body) + "\n")
    print(f"{len(kept)} positions written to {arguments.out} after {attempts} attempts")
    print(f"  -> {2 * len(kept)} distinct games available")
    return 0


if __name__ == "__main__":
    sys.exit(main())
